# -*- coding: utf-8 -*-
"""백준0405

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NGaB4YWu5J5l1nLMZxZzvTkNgXlnta9I
"""

# 9550번
test = int(input())

for i in range(test):
  N, K = map(int, input().split())
  sum = 0
  num_list = list(map(int, input().split()))
  for j in range(N):
    sum += num_list[j] // K
  print(sum)

# 13706번
# 이진 탐색을 이용한 방법.
n = int(input())
left = 1
right = n
while True :
     
  mid = (left + right) // 2

  if mid ** 2 == n:
    print(mid)
    break    
  elif mid ** 2 > n:
    right = mid - 1
  elif mid ** 2 < n:
    left = mid + 1

# 이분탐색
n = int(input())
low = 1
high = n

while 1:
    mid = (low + high) // 2
    if mid ** 2 == n:
        print(mid)
        break
    elif mid ** 2 > n:
        high = mid - 1
    elif mid ** 2 < n:
        low = mid + 1

